NAME := App_Rewair_Local_Bridge

$(NAME)_SOURCES := local_bridge.c \
                   rewair_state.c \
                   rewair_drops.c \
                   rewair_tz.c \
                   rewair_settings.c \
                   rewair_json.c \
                   rewair_api.c \
                   rewair_ble_proto.c \
                   rewair_ble.c \
                   rewair_uifs.c \
                   rewair_fmt.c \
                   rewair_walltime.c \
                   rewair_score.c \
                   rewair_frame_rx.c \
                   rewair_frames.c \
                   rewair_wifi_dct.c \
                   rewair_wifi_scan.c \
                   rewair_wifi_join.c \
                   rewair_net_mode.c \
                   rewair_mqtt.c \
                   rewair_mqtt_packet.c \
                   rewair_ota.c \
                   jsmn.c \
                   web_api.c \
                   web_ui.c \
                   ../../../libraries/protocols/SNTP/sntp.c

# The deterministic RWFS bundle is generated by webui/package.json, copied into
# the SDK by scripts/sync_to_wiced.zsh, and linked into the F411 application as
# a WICED in-memory resource. Firmware OTA therefore carries the matching UI in
# the same raw application image.
$(NAME)_RESOURCES := webui.bin

# USART1 is dedicated to the BI201. Keep newlib's syscall shim so existing
# printf diagnostics link, but WICED_DISABLE_STDIO makes their platform sink a
# no-op and permits the generic UART API to own WICED_UART_1.
$(NAME)_SOURCES += ../../../WICED/platform/GCC/stdio_newlib.c

$(NAME)_INCLUDES := ../../../libraries/protocols/SNTP

$(NAME)_COMPONENTS += daemons/HTTP_server
$(NAME)_COMPONENTS += daemons/DNS_redirect

GLOBAL_DEFINES += JSMN_PARENT_LINKS WICED_DISABLE_STDIO

WIFI_CONFIG_DCT_H := wifi_config_dct.h

VALID_OSNS_COMBOS := FreeRTOS-LwIP
